services:
  postgres:
    container_name: aula-modelagem-dados
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
    volumes:
      - ./dat/postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
